- name: Auto provisions Mac computers
  hosts: localhost
  vars:
    java_version: '21-tem'
    maven_version: '3.9.5'
    python_version: '3.12.0'
    node_version: '21.0.0'
    visual_studio_code_extensions:
      - ms-python.vscode-pylance
      - ms-vscode-remote.remote-containers
      - ms-azuretools.vscode-docker
      - eamodio.gitlens
      - ms-python.python
      - esbenp.prettier-vscode
      - VisualStudioExptTeam.vscodeintellicode
      - dbaeumer.vscode-eslint
    homebrew_packages:
      - cask
      - htop
      - wget
      - midnight-commander
      - speedtest-cli
      - bat
      - terraform
    homebrew_cask_packages:
      - spotify
      - firefox
      - google-chrome
      - docker
      - synology-drive
      - macpass
      - rectangle
      - intellij-idea-ce
      - pycharm-ce
      - darktable
      - gimp
      - inkscape
      - pencil
      - logi-options-plus
      - calibre
      - vlc
      - android-file-transfer
      - utm
      - pulsar
    mac_app_store_packages:
      - 409183694 # Keynote
      - 409203825 # Numbers
      - 409201541 # Pages
      - 1474276998 # HP Smart for Desktop
      - 310633997 # WhatsApp
      - 425424353 # The Unarchiver
    terminal_aliases:
      - upgrade="brew update && brew upgrade && brew upgrade --cask --greedy && mas upgrade"
  roles:
    - oh_my_zsh
    - node
    - python
    - vscode
    - java
    - homebrew
