- hosts: localhost
  vars:
    java_version: '21-tem'
    maven_version: '3.9.5'
    python_version: '3.12.0'
    node_version: '21.0.0'
    visual_studio_code_extensions:
      - ms-python.vscode-pylance
      - ms-vscode-remote.remote-containers
      - ms-azuretools.vscode-docker
      - eamodio.gitlens
      - ms-python.python
    homebrew_packages:
      - cask
    homebrew_cask_packages:
      - spotify
      - firefox
      - google-chrome
      - docker
      - synology-drive
      - macpass
      - rectangle
      - intellij-idea-ce
      - pycharm-ce
      - darktable
      - pencil
  roles:
    - oh-my-zsh
    - node
    - python
    - vscode
    - java
    - homebrew

