- hosts: localhost
  vars:
    java_version: '21-tem'
    maven_version: '3.9.5'
    python_version: '3.12.0'
    node_version: '21.0.0'
    visual_studio_code_extensions:
      - ms-python.vscode-pylance
      - ms-vscode-remote.remote-containers
      - ms-azuretools.vscode-docker
      - eamodio.gitlens
      - ms-python.python
      - esbenp.prettier-vscode
      - VisualStudioExptTeam.vscodeintellicode
      - dbaeumer.vscode-eslint
    homebrew_packages:
      - cask
    homebrew_cask_packages:
      - spotify
      - firefox
      - google-chrome
      - docker
      - synology-drive
      - macpass
      - rectangle
      - intellij-idea-ce
      - pycharm-ce
      - darktable
      - pencil
    mac_app_store_packages:
      - 409183694 # Keynote
      - 409203825 # Numbers
      - 409201541 # Pages
      - 1474276998 # HP Smart for Desktop
      - 310633997 # WhatsApp
  roles:
    - oh-my-zsh
    - node
    - python
    - vscode
    - java
    - homebrew

