---
- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-code
    state: present
- name: Install Visual Studio Code extensions
  shell: "code --install-extension {{ item }} --force"
  args:
    chdir: "{{ ansible_env.HOME }}"
    executable: /bin/zsh
  with_items: "{{visual_studio_code_extensions}}"
