---
- name: Install Oh My Zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
- name: Install zsh-autosuggestions
  community.general.homebrew:
    name: zsh-autosuggestions
    state: present
- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master
- name: Install zsh-synthax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    version: master
- name: Install powerlevel9k
  ansible.builtin.git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel9k"
    version: master
- name: Get powerline fonts
  ansible.builtin.git:
    repo: "https://github.com/powerline/fonts.git"
    dest: "{{ ansible_env.HOME }}/fonts"
    version: master
  notify:
    - Install powerline fonts
- name: Create zsh configuration file
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    owner: "{{ ansible_env.USER }}"
    mode: '0644'
    force: true
- name: Install iTerm2
  community.general.homebrew_cask:
    name: iterm2
    state: present
  notify:
    - Log Font configuration settings
