---
- name: Install pyenv
  community.general.homebrew:
    name: pyenv
    state: present
- name: Create pyenv configuration file
  ansible.builtin.template:
    src: zshrc_include_pyenv.j2
    dest: "{{ ansible_env.HOME }}/.zshrc_include_pyenv"
    owner: "{{ ansible_env.USER }}"
    mode: '0644'
    force: true
- name: Install dependencies to build python
  community.general.homebrew:
    name: "{{ python_packages_needed_to_build_python }}"
    state: present
- name: Install python
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.zshrc && pyenv install {{ python_version }}
  args:
    executable: /bin/zsh
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ python_version }}"
- name: Use the selected python version
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.zshrc && pyenv global {{ python_version }}
  args:
    executable: /bin/zsh
  changed_when: false
