---
- name: Install dependencies
  community.general.homebrew:
    name:
      - cask
      - mas
    state: present
- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: present
- name: Install Homebrew Cask packages
  community.general.homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
- name: Install Mac App store packages
  community.general.mas:
    id: "{{ mac_app_store_packages }}"
    state: present
