---
- name: Install dependencies
  homebrew:
    name:
      - cask
      - mas
    state: present
- name: Install Homebrew packages
  homebrew:
    name: "{{ homebrew_packages }}"
    state: present
- name: Install Homebrew Cask packages
  homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
- name: Install Mac App store packages
  mas:
    id: "{{ mac_app_store_packages }}"
    state: present