---
- name: Install Homebrew packages
  homebrew:
    name: "{{ homebrew_packages }}"
    state: present
- name: Install Homebrew Cask packages
  homebrew_cask:
    name: "{{ homebrew_cask_packages }}"
    state: present
  