---
- name: Install nvm
  homebrew:
    name: nvm
    state: present
- name: Create nvm configuration file
  template:
    src: zshrc_include_nvm.j2
    dest: "{{ ansible_env.HOME }}/.zshrc_include_nvm"
    owner: "{{ ansible_env.USER }}"
    mode: '0644'
    force: yes
- name: Install node
  shell: source {{ ansible_env.HOME }}/.zshrc && nvm install {{ node_version }}
  args:
    executable: /bin/zsh
- name: Use the selected node version
  shell: source {{ ansible_env.HOME }}/.zshrc && nvm install {{ node_version }}
  args:
    executable: /bin/zsh


